//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomIconDashboarderPlugin {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomIconDashboarderPlugin.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current Size.
		/// </summary>
		internal static string hdr_currentSize {
			get {
				return ResourceManager.GetString("hdr_currentSize", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Full Path.
		/// </summary>
		internal static string hdr_fullPath {
			get {
				return ResourceManager.GetString("hdr_fullPath", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Group Name.
		/// </summary>
		internal static string hdr_groupName {
			get {
				return ResourceManager.GetString("hdr_groupName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Icon.
		/// </summary>
		internal static string hdr_icon {
			get {
				return ResourceManager.GetString("hdr_icon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to #Entry.
		/// </summary>
		internal static string hdr_nEntry {
			get {
				return ResourceManager.GetString("hdr_nEntry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Size.
		/// </summary>
		internal static string hdr_newSize {
			get {
				return ResourceManager.GetString("hdr_newSize", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to #Group.
		/// </summary>
		internal static string hdr_nGroup {
			get {
				return ResourceManager.GetString("hdr_nGroup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to #Total.
		/// </summary>
		internal static string hdr_nTotal {
			get {
				return ResourceManager.GetString("hdr_nTotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to #URL.
		/// </summary>
		internal static string hdr_nURL {
			get {
				return ResourceManager.GetString("hdr_nURL", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		internal static string hdr_titleEntry {
			get {
				return ResourceManager.GetString("hdr_titleEntry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Url.
		/// </summary>
		internal static string hdr_url {
			get {
				return ResourceManager.GetString("hdr_url", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to User Name.
		/// </summary>
		internal static string hdr_userName {
			get {
				return ResourceManager.GetString("hdr_userName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Custom Icon Dashboard.
		/// </summary>
		internal static string menu_customIcon {
			get {
				return ResourceManager.GetString("menu_customIcon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Not found.
		/// </summary>
		internal static string val_na {
			get {
				return ResourceManager.GetString("val_na", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No url.
		/// </summary>
		internal static string val_nourl {
			get {
				return ResourceManager.GetString("val_nourl", resourceCulture);
			}
		}
	}
}
