//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomIconDashboarderPlugin {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomIconDashboarderPlugin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Size.
        /// </summary>
        internal static string hdr_currentSize {
            get {
                return ResourceManager.GetString("hdr_currentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Path.
        /// </summary>
        internal static string hdr_fullPath {
            get {
                return ResourceManager.GetString("hdr_fullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.
        /// </summary>
        internal static string hdr_group {
            get {
                return ResourceManager.GetString("hdr_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group Name.
        /// </summary>
        internal static string hdr_groupName {
            get {
                return ResourceManager.GetString("hdr_groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icon.
        /// </summary>
        internal static string hdr_icon {
            get {
                return ResourceManager.GetString("hdr_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id Entry.
        /// </summary>
        internal static string hdr_idEntry {
            get {
                return ResourceManager.GetString("hdr_idEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Entry.
        /// </summary>
        internal static string hdr_nEntry {
            get {
                return ResourceManager.GetString("hdr_nEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Size.
        /// </summary>
        internal static string hdr_newSize {
            get {
                return ResourceManager.GetString("hdr_newSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Group.
        /// </summary>
        internal static string hdr_nGroup {
            get {
                return ResourceManager.GetString("hdr_nGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Total.
        /// </summary>
        internal static string hdr_nTotal {
            get {
                return ResourceManager.GetString("hdr_nTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #URL.
        /// </summary>
        internal static string hdr_nURL {
            get {
                return ResourceManager.GetString("hdr_nURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        internal static string hdr_titleEntry {
            get {
                return ResourceManager.GetString("hdr_titleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Url.
        /// </summary>
        internal static string hdr_url {
            get {
                return ResourceManager.GetString("hdr_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Name.
        /// </summary>
        internal static string hdr_userName {
            get {
                return ResourceManager.GetString("hdr_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Icon Dashboard.
        /// </summary>
        internal static string menu_customIcon {
            get {
                return ResourceManager.GetString("menu_customIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Malformed url.
        /// </summary>
        internal static string val_malformedurl {
            get {
                return ResourceManager.GetString("val_malformedurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not found.
        /// </summary>
        internal static string val_na {
            get {
                return ResourceManager.GetString("val_na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No url.
        /// </summary>
        internal static string val_nourl {
            get {
                return ResourceManager.GetString("val_nourl", resourceCulture);
            }
        }
    }
}
